name: Build and Upload

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Verify files
      run: |
        ls
        if [ ! -f "ui_converter.py" ]; then
          echo "ERROR: ui_converter.py not found!"
          exit 1
        fi

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 pyyaml xmltodict pyinstaller

    - name: Test imports
      run: |
        python -c "from PyQt5.QtWidgets import QApplication; import yaml; import xmltodict; print('All imports OK')"

    - name: Build EXE (with debug)
      run: |
        pyinstaller --onefile --noconsole --log-level DEBUG --name FileConverter.exe ui_converter.py 2>&1 | tee build.log
        type build.log

    - name: Verify EXE
      run: |
        if [ -f "dist/FileConverter.exe" ]; then
          echo "EXE generated successfully"
          ls -lh dist/
        else
          echo "ERROR: EXE not created"
          exit 1
        fi

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: FileConverter
        path: dist/FileConverter.exe