name: Build and Upload

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Verify files (Windows compatible)
      run: |
        dir  # Lista plików
        if not exist "ui_converter.py" (
          echo ERROR: ui_converter.py not found!
          exit 1
        )

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 pyyaml xmltodict pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile --noconsole --name FileConverter.exe ui_converter.py

    - name: Verify EXE (Windows style)
      run: |
        if exist "dist\FileConverter.exe" (
          echo EXE generated successfully
          dir dist\
        ) else (
          echo ERROR: EXE not created
          exit 1
        )

    - uses: actions/upload-artifact@v4
      with:
        name: FileConverter
        path: dist\FileConverter.exe