name: Build IT Tools Converter  # Nazwa workflow (wyświetlana w GitHub Actions)

on:
  push:
    branches: [ "master" ]     # Uruchamia się po pushu na branch 'master'
  schedule:
    - cron: '0 0 * * 1'       # Uruchamia się w każdy poniedziałek o 00:00 (GMT)
  workflow_dispatch:           # Ręczne uruchomienie w zakładce Actions

jobs:
  build:
    runs-on: windows-latest    # Używa najnowszej wersji Windowsa

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Dostosuj do swojej wersji Pythona

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install pyyaml xmltodict  # Biblioteki do obsługi formatów
          # Uruchomienie skryptu installResources.ps1 (jeśli istnieje)
          if (Test-Path -Path "installResources.ps1") {
            ./installResources.ps1
          }

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --noconsole project.py

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: IT-Tools-Converter
          path: dist/project.exe  # Ścieżka do wygenerowanego pliku .exe